const cars = [
	{
		id: 1,
		brand: "Toyota",
		model: "Corolla",
		productionYear: 2020,
		imageURL: "https://cdn.motor1.com/images/mgl/O0M0b/s1/toyota-corolla.jpg",
		kilometers: 142000,
		dealerId: 1,
	},
	{
		id: 2,
		brand: "Ford",
		model: "Focus",
		productionYear: 2018,
		imageURL: "https://cdn.motor1.com/images/mgl/BEooz/s1/ford-focus.jpg",
		kilometers: 217000,
		dealerId: 1,
	},
	{
		id: 3,
		brand: "Honda",
		model: "Civic",
		productionYear: 2021,
		imageURL: "https://cdn.motor1.com/images/mgl/QE1x9/s1/honda-civic.jpg",
		kilometers: 118000,
		dealerId: 1,
	},
	{
		id: 4,
		brand: "Chevrolet",
		model: "Malibu",
		productionYear: 2019,
		imageURL: "https://cdn.motor1.com/images/mgl/rK7eM/s1/chevrolet-malibu.jpg",
		kilometers: 189000,
		dealerId: 2,
	},
	{
		id: 5,
		brand: "BMW",
		model: "320i",
		productionYear: 2022,
		imageURL: "https://cdn.motor1.com/images/mgl/W88oN/s1/bmw-320i.jpg",
		kilometers: 101000,
		dealerId: 2,
	},
	{
		id: 6,
		brand: "Opel",
		model: "Astra",
		productionYear: 2016,
		imageURL: "https://cdn.motor1.com/images/mgl/8M0W3/s1/opel-astra.jpg",
		kilometers: 312000,
		dealerId: 2,
	},
	{
		id: 7,
		brand: "Audi",
		model: "A4",
		productionYear: 2020,
		imageURL: "https://cdn.motor1.com/images/mgl/JP7Yo/s1/audi-a4.jpg",
		kilometers: 168000,
		dealerId: 2,
	},
	{
		id: 8,
		brand: "Mercedes-Benz",
		model: "C-Class",
		productionYear: 2017,
		imageURL: "https://cdn.motor1.com/images/mgl/Znn6p/s1/mercedes-c-class.jpg",
		kilometers: 271000,
		dealerId: 3,
	},
	{
		id: 9,
		brand: "Nissan",
		model: "Altima",
		productionYear: 2021,
		imageURL: "https://cdn.motor1.com/images/mgl/y8P6k/s1/nissan-altima.jpg",
		kilometers: 134000,
		dealerId: 3,
	},
	{
		id: 10,
		brand: "Hyundai",
		model: "Elantra",
		productionYear: 2022,
		imageURL: "https://cdn.motor1.com/images/mgl/RGJ4W/s1/hyundai-elantra.jpg",
		kilometers: 109000,
		dealerId: 3,
	},
	{
		id: 11,
		brand: "Ford",
		model: "Fiesta",
		productionYear: 2015,
		imageURL: "https://cdn.motor1.com/images/mgl/PK7Oz/s1/ford-fiesta.jpg",
		kilometers: 356000,
		dealerId: 4,
	},
	{
		id: 12,
		brand: "Nissan",
		model: "Leaf",
		productionYear: 2023,
		imageURL: "https://cdn.motor1.com/images/mgl/xE3Rj/s1/nissan-leaf.jpg",
		kilometers: 102000,
		dealerId: 4,
	},
	{
		id: 14,
		brand: "Audi",
		model: "TT",
		productionYear: 2011,
		imageURL: "https://cdn.motor1.com/images/mgl/2vVn7/s1/audi-tt.jpg",
		kilometers: 379000,
		dealerId: 5,
	},
	{
		id: 15,
		brand: "Honda",
		model: "Jazz",
		productionYear: 2015,
		imageURL: "https://cdn.motor1.com/images/mgl/g3r9K/s1/honda-jazz.jpg",
		kilometers: 287000,
		dealerId: 5,
	},
	{
		id: 16,
		brand: "Opel",
		model: "Mokka",
		productionYear: 2024,
		imageURL: "https://cdn.motor1.com/images/mgl/BE2nL/s1/opel-mokka.jpg",
		kilometers: 100000,
		dealerId: 5,
	},
	{
		id: 17,
		brand: "Toyota",
		model: "RAV4",
		productionYear: 2014,
		imageURL: "https://cdn.motor1.com/images/mgl/eYwZ7/s1/toyota-rav4.jpg",
		kilometers: 341000,
		dealerId: 6,
	},
];

const dealers = [
	{
		id: 1,
		name: "Stefanov",
		address: "123 Main St",
		workingHours: "Mon-Fri 8-17",
		cars: [1, 3, 5],
	},
	{
		id: 2,
		name: "Renault",
		address: "456 Trud",
		workingHours: "Mon-Fri 9-18",
		cars: [6, 7],
	},
	{
		id: 3,
		name: "Gema96",
		address: "456 Smirnenski",
		workingHours: "Mon-Sat 9-18",
		cars: [8, 9, 10],
	},
	{
		id: 4,
		name: "Moto Phoe",
		address: "101 Trakia",
		workingHours: "Mon-Fri 9-18",
		cars: [11, 12],
	},
	{
		id: 5,
		name: "AutoHome",
		address: "101 Gagarin",
		workingHours: "Mon-Fri 9-18",
		cars: [13, 14, 15, 16],
	},
	{
		id: 6,
		name: "Peugeot",
		address: "101 Trud",
		workingHours: "Mon-Fri 9-18",
		cars: [17],
	},
];

module.exports = { cars, dealers };
